services:
  app1: &app
    build: .
    hostname: app1
    environment:
      PORT: 8080
      NODE_ENV: production
      CLUSTER: true
      CLUSTER_WORKERS: 5
    expose:
      - "8080"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.8GB'

  app2:
    <<: *app
    hostname: app2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: yourpassword
    command: ["redis-server", "--requirepass", "yourpassword"]
    deploy:
      resources:
          limits:
              cpus: '0.1'
              memory: '0.2GB'